### ISSUE TITLE
Container Images

### ISSUE THREAD

**Issue by ScottGuymer** [sethvargo/ratchet#12]
### TL;DR

The readme indicates there are containers and has a link but there are none there.

**Comment by sethvargo** [comment]
Hi @ScottGuymer 

Thank you for opening an issue. I'm not sure what you mean. The link in the README points to https://github.com/sethvargo/ratchet/pkgs/container/ratchet, which lists all the container images:

<img width="1017" alt="screenshot-20220520-kjkzskIn@2x" src="https://user-images.githubusercontent.com/408570/169559274-07eb74ab-2f62-4db0-90a3-d25bf80f8cf1.png">

Are you seeing something different?

**Comment by ScottGuymer** [comment]
Thats is really strange...

I was seeing an empty page with no packages...

I guess it was a GH blip, wish I had taken a screenshot now..

Sorry about that
