### ISSUE TITLE
Homebrew support?

### ISSUE THREAD

**Issue by mwarkentin** [sethvargo/ratchet#32]
### TL;DR

It would be nice to have a simple `brew install ratchet` available in order to install on MacOS.

### Additional information

* https://docs.brew.sh/Adding-Software-to-Homebrew
* https://docs.brew.sh/Formula-Cookbook
* https://docs.brew.sh/Manpage#create-options-url

**Comment by sethvargo** [comment]
Hi @mwarkentin 

Thank you for opening a Pull Request. I've had a terrible experience trying to get new cookbooks (or patches to existing cookbooks) in Homebrew, and I don't have the bandwidth to fight with upstream on this. If someone from the community wants to take this work on, great, but I will not be devoting effort to creating a cookbook or cask for Ratchet. Sorry!

**Comment by mwarkentin** [comment]
No worries, I'll see if I can take a crack at it. 😊
