### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by jksolbakken** [sethvargo/ratchet#48]
### New issue?

- [X] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

### TL;DR

Thank you for making a great tool! It's a bit cumbersome to install and upgrade it manually though, have you considered creating a Homebrew tap and/or an asdf plugin?

**Comment by sethvargo** [comment]
Duplicate of https://github.com/sethvargo/ratchet/issues/32.
