### ISSUE TITLE
In `ratchet --version` output, please show real version (e.g. `0.5.0`) instead of `devel`

### ISSUE THREAD

**Issue by nitrocode** [sethvargo/ratchet#58]
### New issue?

- [X] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

### TL;DR

I downloaded the binary from the releases page and see `devel` in the version output instead of `0.5.0`

### Expected behavior

```
✗ ratchet --version
ratchet (0.5.0) (df0adb51bf6adce7a81095187c482de72c2d0e9d, darwin/amd64)
```

### Observed behavior

```
✗ ratchet --version
ratchet (devel) (df0adb51bf6adce7a81095187c482de72c2d0e9d, darwin/amd64)
```

### Version

0.5.0

### On what operating system are you using ratchet?

Mac OS

**Comment by sethvargo** [comment]
How did you install ratchet?

**Comment by nitrocode** [comment]
I downloaded the release from the github releases page.

```bash
wget https://github.com/sethvargo/ratchet/releases/download/v0.5.0/ratchet_0.5.0_darwin_$(uname -m).tar.gz
tar xvfz ratchet_0.5.0_darwin_$(uname -m).tar.gz
sudo mv ratchet /usr/local/bin
which ratchet
ratchet --version
```

**Comment by sethvargo** [comment]
Well, that was quite a rollercoaster of discovery: https://github.com/golang/go/issues/64246

**Comment by nitrocode** [comment]
Thanks for hunting that down and fixing it
