### ISSUE TITLE
Allow pinning internal actions

### ISSUE THREAD

**Issue by nitrocode** [sethvargo/ratchet#60]
### New issue?

- [X] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

### TL;DR

For internal/private repos, pinning actions would be nice

```bash
✗ ratchet pin .github/workflows/snip.yml
failed to pin refs: 1 error occurred:
	* failed to resolve "actions://org/repo/snip/action.yml@snip-v1.0.1": failed to get commit sha: GET https://api.github.com/repos/org/repo/commits/snip-v1.0.1: 404 Not Found []
```

A workaround for myself is to use [mheap/pin-github-action](https://github.com/mheap/pin-github-action). I'd like to use `ratchet` since that's what I currently use for open source actions.

```bash
export GH_ADMIN_TOKEN=$(gh config get -h github.com oauth_token)
pin-github-action .github/workflows/snip.yml
```

### Detailed design

```markdown
See above
```

### Additional information

See above

**Comment by sethvargo** [comment]
Hi @nitrocode what do you mean by "internal" action? Is this on a private GitHub Enterprise Server (behind the firewall), or is this a private repo on GitHub.com?

You should be able to do the same with ratchet:

```sh
export ACTIONS_TOKEN=$(gh config get -h github.com oauth_token)
ratchet ./
```

**Comment by nitrocode** [comment]
Oh I meant private repo on github.com.

I did not know I could use that env var. Thank you!
