### ISSUE TITLE
Create different comment style

### ISSUE THREAD

**Issue by stdedos** [sethvargo/ratchet#82]
### New issue?

- [X] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

### TL;DR

It seems that dependabot supports updating version comments as part of its update https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/

However, can the comments look more like https://github.com/pyca/cryptography/pull/10650/files?
I don't know if dependabot would support the `ratchet:` comments :confused:

**Comment by sethvargo** [comment]
Hi @stdedos - Ratchet supports more than that GitHub Actions. It would be better to ask dependabot to look for the the ratchet prefix: https://github.com/dependabot/dependabot-core/pull/5951/files#diff-e610ea8f33cbfe74ada7eb6fbeab2afe2e2dad154e191bb209fb69f6ca3d7137R77

**Comment by stdedos** [comment]
_Please don't call it completed_ 😅

**Comment by sethvargo** [comment]
That's what GitHub does when you close an issue by default.

**Comment by stdedos** [comment]
There is always https://github.com/refined-github/refined-github/blob/main/source/features/close-as-unplanned.tsx for the utility that Github is _not_ adding 😅
