### ISSUE TITLE
ratchet has been submitted for inclusion in nixpkgs but has not been merged

### ISSUE THREAD

**Issue by cameronraysmith** [sethvargo/ratchet#83]
- [X] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

In case others are interested in being able to install ratchet via nix, it has been submitted twice in

- https://github.com/NixOS/nixpkgs/pull/282464
- https://github.com/NixOS/nixpkgs/pull/311799

Feel free to close this issue; however, I will otherwise plan to close it when one of those or another similar PR is merged into nixpkgs.

**Comment by sethvargo** [comment]
Hi @cameronraysmith - thanks. Do you need anything from me?

**Comment by sethvargo** [comment]
Nothing in the `parser` package should talk to the internet. The only package with egress is `resolver`, and it _should_ be restricted to specific IPs. For example, you could set `ACTIONS_BASE_URL` and `ACTIONS_UPLOAD_URL` to a localhost address in tests. Container registries are more difficult to override for testing.

But yes, only `TestLatestVersion` and `TestResolve` should talk to the Internet.

**Comment by cameronraysmith** [comment]
https://github.com/NixOS/nixpkgs/pull/311799
