### ISSUE TITLE
Custom comment format to be compatible with yamllint and dependabot

### ISSUE THREAD

**Issue by prein** [sethvargo/ratchet#89]
### New issue?

- [X] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

### TL;DR

Current comment format is not compatible with yamllint and dependabot

### Detailed design

```markdown
YAMLlint wants two spaces before comments. Yes, I am aware that I can configure yamllint to want 1 space, but if it's possible to make ratchet comply it would make it easier for me.

I use both ratchet and dependabot. Dependabot supports updating version comments but only selection of formats - see https://github.com/dependabot/dependabot-core/pull/5951/files#diff-fd484a22a8411825b6409071a0d839654c9629162c27b0be71e6abe7b7a8d08bR7-R16
If it was possible to customize the comment format it would save me time and effort
```

### Additional information

Thanks for taking the time to review my requests :)

**Comment by sethvargo** [comment]
This is a [function](https://github.com/sethvargo/ratchet/blob/ebb7f24e0cbc288ab913b635480412934a2a5371/parser/parser.go#L162) of the upstream YAML parser and writer that we use. There's no option to control this spacing.
